### ISSUE TITLE
help server throws `NoSuchMethodError`

### ISSUE THREAD

**Issue by martinlippert** [eclipse-platform/eclipse.platform#2125]
Running 2025-09 M2 JEE package, and saw this appearing as an error:

```
java.lang.NoSuchMethodError: 'org.eclipse.jetty.util.component.Environment org.eclipse.jetty.util.component.Environment.ensure(java.lang.String)'
	at org.eclipse.jetty.ee8.nested.ContextHandler.<clinit>(ContextHandler.java:145)
	at org.eclipse.equinox.http.jetty.internal.HttpServerManager.createHttpContext(HttpServerManager.java:261)
	at org.eclipse.equinox.http.jetty.internal.HttpServerManager.updated(HttpServerManager.java:171)
	at org.eclipse.equinox.http.jetty.internal.Activator.startServer(Activator.java:256)
	at org.eclipse.equinox.http.jetty.JettyConfigurator.startServer(JettyConfigurator.java:52)
	at org.eclipse.help.internal.server.JettyHelpServer$StartServerThread.run(JettyHelpServer.java:84)
```

**Comment by martinlippert** [comment]
Actually, I am wrong, this was not a plain 2025-09 installation, but a 2025-06 one that I updated to the latest 2025-09 staging repo content. Maybe something went wrong along those lines.

**Comment by laeubi** [comment]
I would assume that some of the version ranges are not properly reflecting what actually is used/needed. It might then happen that eclipse claims to support some older API what it actually does not.

Can you check what exact versions of the help center and jetty is installed in your setup?

**Comment by martinlippert** [comment]
Sure, here are the details:

Help center:
```
org.eclipse.help_3.10.600.v20250613-0437
org.eclipse.help.base_4.5.200.v20250814-1800
org.eclipse.help.ui_4.8.200.v20250707-1559
org.eclipse.help.webapp_3.12.200.v20250710-0643
```

Jetty:
```
org.eclipse.jetty.ee_12.0.25
org.eclipse.jetty.ee8.annotations_12.0.25
org.eclipse.jetty.ee8.jndi_12.0.25
org.eclipse.jetty.ee8.plus_12.0.25
org.eclipse.jetty.ee8.security_12.0.25
org.eclipse.jetty.ee8.server_12.0.25
org.eclipse.jetty.ee8.servlet_12.0.25
org.eclipse.jetty.ee8.servlets_12.0.25
org.eclipse.jetty.ee8.webapp_12.0.25
org.eclipse.jetty.http_12.1.0
org.eclipse.jetty.io_12.1.0
org.eclipse.jetty.jndi_12.0.25
org.eclipse.jetty.plus_12.0.25
org.eclipse.jetty.security_12.1.0
org.eclipse.jetty.server_12.1.0
org.eclipse.jetty.session_12.0.25
org.eclipse.jetty.util_12.1.0
org.eclipse.jetty.xml_12.0.25
```

**Comment by akurtakov** [comment]
That's a wild mixture of 12.0.25 and 12.1.0 and I would bet that's the problem.

**Comment by martinlippert** [comment]
And it looks like this wild mix ended up in my installation as a result of an update (using the 2025-09 staging repo, which also contains the mix of versions). The product that we build from the same staging repo contains the `12.0.25` versions only.

**Comment by merks** [comment]
It's a pretty wild mixture.

<img width="556" height="565" alt="Image" src="https://github.com/user-attachments/assets/369b9388-52a0-4a1a-b9f1-db884e2bd1ff" />

With EGit having picked up 12.0.1, the Platform and WTP, on 12.0.25, and RAP on 12.0.23.  

I just can't get people to stop including 3rd party bundles in the features.  I've tried, and tried, and we made a new rule, but still it persists.

<img width="633" height="80" alt="Image" src="https://github.com/user-attachments/assets/b084ab4f-ff1c-4096-8576-b4e512d45d52" />

<img width="676" height="65" alt="Image" src="https://github.com/user-attachments/assets/01cabde4-83ae-417b-a589-aa0dabc0f8bf" />

Maybe it will improve somewhat when RAP updates which is generally quite last minute.

In any case, this does not appear to be a bug in the platform.  It seems Jetty is not defining proper ranges and projects just insist on include a specific version such that we end up with duplicates and bad combinations each time there is an update.

Also I have been trying to build 12.0.1 in Orbit but strange dependency errors are blocking my effort (and copilot distractions have not been helpful).

**Comment by laeubi** [comment]
I suspect that the case and its of course not nice to have such a wild mixture here. But in any case it should work, so if there is an issue at jetty do we have a report for them so they can improve the situation there? Looking at the code it seems strange to get such error if their lower bounds are actually should be correct.

@martinlippert can you please show what the `wires` command gives you for `org.eclipse.jetty.ee8.server` bundle that is currently wired to `org.eclipse.equinox.http.jetty`?

Could you even export the current state with `exportFrameworkState <path to store the data> true`? We should really try to understand why this issue is there and it is correctly addressed (at least reported), therefore I reopen the issue for now.

**Comment by merks** [comment]
Note that the 12.0.25 version will allow the 12.1.0 version of the dependency

<img width="422" height="957" alt="Image" src="https://github.com/user-attachments/assets/b1a3d91f-05b1-449e-972d-20eb6ef9a056" />

I'm currently debugging a problem in BIRT testing 12.1.0.  Here I see classes in 

https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-deploy/12.0.25/

are actually deleted in 

https://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-deploy/12.1.0/

E.g., DeploymentManager is gone:

<img width="1007" height="467" alt="Image" src="https://github.com/user-attachments/assets/3666e0b8-b0a4-4a59-b6e6-d189a792189c" />

So this is clearly not API compatible.  So I suspect there are other places that are fast and lose with deleting things that are API...

**Comment by laeubi** [comment]
@merks if we find out it is unavoidable it is fine, but the error looks suspicious to me.

It complains about not finding a method in `ContextHandler` static initializer that is from a class in jetty-util. If we now assume they did add it in a more recent version the lower version bound should have prevent any issues. I therefore looking forward to capture a real state dump from the problem to at least prove it is not an Equinox issue :-)

**Comment by merks** [comment]
In the latest version the calls I like this:

<img width="1056" height="748" alt="Image" src="https://github.com/user-attachments/assets/04631982-c360-4acc-81b2-9a5cfeb6f953" />

But they're calling from the 12.0.25 version of the former into the 12.1.0 version of the latter:

<img width="690" height="277" alt="Image" src="https://github.com/user-attachments/assets/baa846f4-538a-42db-9418-a0dd300669b5" />

It's a single argument method but the receiver now only has a two argument method. 

So the upper bound is too lose if they're doing to remove methods when making only a minor version increment.

There is really nothing to fix in the Platform, instead

- It's a problem with Jetty's range being to permissive relative to their API-breaking changes for minor increments.
- It's a problem in SimRel that we're installing a mixture of versions.

It _might_ help to change all the lower bounds to 12.1.0 and it wouldn't hurt to do that.  Edit...  I take the "wouldn't hurt comment back".  It might just hurt in a different place if a (different) combination is still installed.

**Comment by laeubi** [comment]
This is indeed not so good and should be reported to jetty, it seem they do not properly baseline their artifacts nor does they seem to use proper version ranges.

Still it feels a bit strange that the resolver is choosing that combination at all, it should wire the highest version of everything and not mix up things unnecessarily.

So if it is reproducible a state dump would still be helpful here, also it would be interesting to see if `-clean` can fix the issue.

**Comment by merks** [comment]
Nothing can fix the issue because I did a scratch install and there is only one version of each bundle installed.

<img width="936" height="283" alt="Image" src="https://github.com/user-attachments/assets/ca9f32af-998a-4ad0-b606-7fa365422d91" />

They cannot be alternatively wired and it's clear that 12.0.25 versions cannot be assumed to work with 12.1.0 versions because they're not doing proper semantic versioning.

Away, Jetty and associated problems have consumed my entire day, I've opened one defect already, and I'm sure there are many more issues in their stuff with the current approach of specifying `13.0.0)` and then blithely deleting API.  I would seem better for version `x.y.0` to use upper bound `x.y+1.0 `to ensure that the whole combination is always in a state based on what was tested and released together.  You may wish to try to educate them on this topic.

**Comment by merks** [comment]
FYI, I verified that help works with the current staging (with Platform's RC1) where there is a mixture of 12.1.0 and 12.0.25 in the staging repo and and installed in the JEE IDE:

<img width="987" height="1174" alt="Image" src="https://github.com/user-attachments/assets/d6a44b5d-a6fd-4a6b-a938-b7de10cf0c1e" />

**Comment by Phillipus** [comment]
Sorry to intrude on this but I just came across this issue because I am trying to use the latest JGit (7.4) in an RCP app based on Eclipse 4.32. This error occurs when opening a Help window in the RCP app:

```
java.lang.NoSuchMethodError: 'org.eclipse.jetty.util.component.Environment org.eclipse.jetty.util.component.Environment.ensure(java.lang.String)'
	at org.eclipse.jetty.ee8.nested.ContextHandler.<clinit>(ContextHandler.java:141)
	at org.eclipse.equinox.http.jetty.internal.HttpServerManager.createHttpContext(HttpServerManager.java:253)
	at org.eclipse.equinox.http.jetty.internal.HttpServerManager.updated(HttpServerManager.java:164)
	at org.eclipse.equinox.http.jetty.internal.Activator.startServer(Activator.java:240)
	at org.eclipse.equinox.http.jetty.JettyConfigurator.startServer(JettyConfigurator.java:52)
	at org.eclipse.help.internal.server.JettyHelpServer$StartServerThread.run(JettyHelpServer.java:84)
```

The update site for JGit is [this one](https://download.eclipse.org/egit/updates-7.4/) and it contains `org.eclipse.jetty.util_12.1.0.jar` which is being added to the RCP app and causes the the error whenever I try to open a Help window in the RCP app.

So a quick question (perhaps for @merks ?) - is there any way round this or do I have to target an older version of JGit or a later Eclipse version for the RCP app? Ideally I would like to target only the immediate dependencies of JGit and and not pull in the Jetty stuff:

```
<target name="Target">
<locations>
    <location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
        <repository location="https://download.eclipse.org/releases/2024-06"/>
        <unit id="org.eclipse.sdk.ide" version="4.32.0.I20240601-0610"/>
        <unit id="org.eclipse.emf.compare.feature.group" version="3.3.24.202401051648"/>
    </location>
    <location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
        <repository location="https://download.eclipse.org/egit/updates-7.4"/>
        <unit id="org.eclipse.jgit.feature.group" version="7.4.0.202509020913-r"/>
        <unit id="org.eclipse.jgit.ssh.apache.feature.group" version="7.4.0.202509020913-r"/>
        <unit id="org.eclipse.jgit.gpg.bc.feature.group" version="7.4.0.202509020913-r"/>
    </location>
    <location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
        <repository location="https://download.eclipse.org/eclipse/updates/4.32"/>
        <unit id="org.mockito.mockito-core" version="5.12.0"/>
    </location>
</locations>
</target>
```

Edit - actually I get the same error when targetting `https://download.eclipse.org/releases/2025-06` but `https://download.eclipse.org/staging/2025-09/` is OK.

**Comment by merks** [comment]
All of JGit dependencies on Jetty allow `[12.0.0,13.0.0)`.   The problematic thing is a combination of 12.1.0 with 12.0.x.  So you need to ensure that you either end up installing all 12.0.x or all 12.1.0.

So check what ends up in your target platform. 

Maybe one of these is helpful:

https://download.eclipse.org/tools/orbit/simrel/maven-jetty/

I would start by trying to ensure that 12.1.0 is available for all required bundles because p2 will generally install the latest one.  Trying to restrict all to 12.0.25 is more tricky and then you might need to use some p2.inf with negative requirements to exclude higher versions.

Here's what's pulled into SimRel by various requirements:

<img width="271" height="441" alt="Image" src="https://github.com/user-attachments/assets/b280bfcb-4c28-4e66-871d-64acb76d339c" />

**Comment by Phillipus** [comment]
I think for our RCP app we will, for now, continue to target JGit 6.10 and possibly 7.3.0 (which has Jetty 12.0.21). At some point I need to update our RCP app so it targets Eclipse 4.37 (2025-09) or later and at that point we can target JGit 7.4.0.

Thank @merks for your help, as always I greatly appreciate it.

**Comment by laeubi** [comment]
@Phillipus you might want to ask jgit to raise their lower bounds like platform did to exclude the bad jetty version.

**Comment by Phillipus** [comment]
> [@Phillipus](https://github.com/Phillipus) you might want to ask jgit to raise their lower bounds like platform did to exclude the bad jetty version.

Thanks for the suggestion. I opened https://github.com/eclipse-jgit/jgit/issues/209
