### PR TITLE
buildExtraJAR: use Java 17 - fixes #570

### LINKED ISSUE #570: Ant support library build broken
Compilation error in IDE running `eclipse.platform/resources/bundles/org.eclipse.core.resources/scripts/buildExtraJAR.xml`

Caused by 26abe910ee70ab5c1f74d4ba620ea039478531b9.

```
       [javac] ----------
       [javac] 1. ERROR in /data/git/eclipse.platform/resources/bundles/org.eclipse.core.resources/src_ant/org/eclipse/core/resources/ant/ConvertPath.java (at line 144)
       [javac] 	fileSystemPath = IPath.fromOSString(value.toString());
       [javac] 	                       ^^^^^^^^^^^^
       [javac] References to interface static methods are allowed only at source level 1.8 or above
       [javac] ----------
       [javac] 2. ERROR in /data/git/eclipse.platform/resources/bundles/org.eclipse.core.resources/src_ant/org/eclipse/core/resources/ant/ConvertPath.java (at line 155)
       [javac] 	resourcePath = IPath.fromOSString(value);
       [javac] 	                     ^^^^^^^^^^^^
       [javac] References to interface static methods are allowed only at source level 1.8 or above
       [javac] ----------
       [javac] ----------
       [javac] 3. ERROR in /data/git/eclipse.platform/resources/bundles/org.eclipse.core.resources/src_ant/org/eclipse/core/resources/ant/RefreshLocalTask.java (at line 113)
       [javac] 	IPath path = IPath.fromOSString(value);
       [javac] 	                   ^^^^^^^^^^^^
       [javac] References to interface static methods are allowed only at source level 1.8 or above
       [javac] ----------
       [javac] 3 problems (3 errors)

BUILD FAILED
/data/git/eclipse.platform/resources/bundles/org.eclipse.core.resources/scripts/buildExtraJAR.xml:38: Compile failed; see the compiler error output for details.
```

### PR DESCRIPTION
**Pull request by jukzi**
https://github.com/eclipse-platform/eclipse.platform/issues/570

### CODE REVIEW

**Comment by jukzi** [comment]
@SarikaSinha is it ok to update this to 17? or should it be 11?  (https://github.com/eclipse-platform/eclipse.platform/issues/411)

**Comment by SarikaSinha** [comment]
> @SarikaSinha is it ok to update this to 17? or should it be 11? (#411)

It should be at 11. All the remote jars etc for Ant are built with 11.
It is used quite often  in headless mode.

**Comment by HannesWell** [comment]
Thanks Jörg for the fix.

> > @SarikaSinha is it ok to update this to 17? or should it be 11? (#411)
> 
> It should be at 11. All the remote jars etc for Ant are built with 11.
> It is used quite often  in headless mode.

If I didn't miss something the ant jars have dependencies to classes/Interfaces compiled with Java-17, e.g. IPath.
Therefore I assume one needs Java-17 anyways and we could use it here too?
