### ISSUE TITLE
Ant support library build broken

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#570]
Compilation error in IDE running `eclipse.platform/resources/bundles/org.eclipse.core.resources/scripts/buildExtraJAR.xml`

Caused by 26abe910ee70ab5c1f74d4ba620ea039478531b9.

```
       [javac] ----------
       [javac] 1. ERROR in /data/git/eclipse.platform/resources/bundles/org.eclipse.core.resources/src_ant/org/eclipse/core/resources/ant/ConvertPath.java (at line 144)
       [javac] 	fileSystemPath = IPath.fromOSString(value.toString());
       [javac] 	                       ^^^^^^^^^^^^
       [javac] References to interface static methods are allowed only at source level 1.8 or above
       [javac] ----------
       [javac] 2. ERROR in /data/git/eclipse.platform/resources/bundles/org.eclipse.core.resources/src_ant/org/eclipse/core/resources/ant/ConvertPath.java (at line 155)
       [javac] 	resourcePath = IPath.fromOSString(value);
       [javac] 	                     ^^^^^^^^^^^^
       [javac] References to interface static methods are allowed only at source level 1.8 or above
       [javac] ----------
       [javac] ----------
       [javac] 3. ERROR in /data/git/eclipse.platform/resources/bundles/org.eclipse.core.resources/src_ant/org/eclipse/core/resources/ant/RefreshLocalTask.java (at line 113)
       [javac] 	IPath path = IPath.fromOSString(value);
       [javac] 	                   ^^^^^^^^^^^^
       [javac] References to interface static methods are allowed only at source level 1.8 or above
       [javac] ----------
       [javac] 3 problems (3 errors)

BUILD FAILED
/data/git/eclipse.platform/resources/bundles/org.eclipse.core.resources/scripts/buildExtraJAR.xml:38: Compile failed; see the compiler error output for details.
```

**Comment by iloveeclipse** [comment]
@laeubi : I assume ant_tasks/resources-ant.jar that is included **inside** org.eclipse.core.resources_XYZ.jar is **somehow** built by tycho because of `source.ant_tasks/resources-ant.jar=src_ant/` line in build.properties file.

But since this can't be built on command line, how tycho builds it? Does it ignore "target" setting and just builds using Java 17?

@HannesWell : FYI.

**Comment by iloveeclipse** [comment]
> and then a "library" is created here

How exactly tycho creates this library? Using project JLS from manifest?

**Comment by HannesWell** [comment]
That's annoying. I can revert that change for java files in a `src_ant` folder this evening.
Or can we lift the requirement for ant-tasks to at least Java-1.8?
Since Eclipse SDK require Java-17 I assumed that this also applies to the ANT-tasks?

**Comment by iloveeclipse** [comment]
> Or can we lift the requirement for ant-tasks to at least Java-1.8?

Ant is allowed to be executed also with different JDK as the host, similar to debug tooling that can debug any JDK available.

So we can for sure update that **somewhere**, currently I simply can't understand **how** the library is actually built - if that is built using Java 17, there shouldn't be issues - except we have **yet another** library that (silently) can't be built now.

The `scripts/buildExtraJAR.xml` isn't referenced by maven/tycho as far as I can see, so the compilation fail in the IDE is just a hint that 26abe910ee70ab5c1f74d4ba620ea039478531b9 could be the root cause of some "obscure" ancient build artifacts we still have & use.

**Comment by iloveeclipse** [comment]
Actually ant.launching shows already an error that Java 11 is required if one tries to run ant with Java 8 from Eclipse, since 5a8c086442f44719d0edf8af84b177baee0d8a49

**Comment by HannesWell** [comment]
> Compilation error in IDE running `eclipse.platform/resources/bundles/org.eclipse.core.resources/scripts/buildExtraJAR.xml`

I did not yet manage to run that script until the point to get the same error.
I tried `Right-Click -> Run As -> Ant Build ...` and added as argument `-Declipse.home=<my-local-p2-bundle-pool>`. Is there more do to? E.g. configure a special JRE?

> Actually ant.launching shows already an error that Java 11 is required if one tries to run ant with Java 8 from Eclipse, since [5a8c086](https://github.com/eclipse-platform/eclipse.platform/commit/5a8c086442f44719d0edf8af84b177baee0d8a49)

I encountered that as well. But then I get the failure that java-1.5 is not supported anymore and that I should use at least Java 6.

So because of that and since dependencies are already targeting Java-17 I wonder if we can't just lift the source/target to 17 in
https://github.com/eclipse-platform/eclipse.platform/blob/972581d8c6ce4b5b2b7142a91dd25392014d10b3/resources/bundles/org.eclipse.core.resources/scripts/buildExtraJAR.xml#L38

Besides in o.e.core.resources build.properties I see the warning `Source folders 'src/,src_ant/' share the same output folder but are targeted to different libraries.`. Therefore I wonder if something should be fix there and if the currently produced jars are flaky, i.e. contain too many classes.
